baseURL = "https://nice-field-0e3c5fd0f-2.eastus2.1.azurestaticapps.net/"
languageCode = "en-us"
title = "Feline Good BI Docs"

[module]

    [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
